on: pull_request_review
name: Pull Request Labeller
jobs:
  labelWhenApproved:
    name: Label PR When approved
    runs-on: ubuntu-latest
    steps:
    - name: Label PR when approved
      uses: pullreminders/label-when-approved-action@master
      env:
        APPROVALS: "1"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ADD_LABEL: "approved"
        #REMOVE_LABEL: "awaiting%20review"
